// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpineTreeNodeKind } from "../SpineTreeNodeKind";
import type { SpineTreeNodeStatus } from "../SpineTreeNodeStatus";
import type { SpineNodeContextPressure } from "./SpineNodeContextPressure";

export type SpineTreeNode = { nodeId: string, parentId: string | null, kind: SpineTreeNodeKind, status: SpineTreeNodeStatus, summary: string | null, memorySummary: string | null, start: bigint, end: bigint | null, contextPressure: SpineNodeContextPressure | null, };
