// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpineNodeContextBaselineSource } from "./SpineNodeContextBaselineSource";
import type { SpineNodeContextProblem } from "./SpineNodeContextProblem";

export type SpineTreeNodeAccounting = { currentNodeContextTokens: bigint | null, currentNodeContextProblem: SpineNodeContextProblem | null, currentNodeContextBaselineSource: SpineNodeContextBaselineSource | null, closedSourceSuffixTokens: bigint | null, closedMemoryContextTokens: bigint | null, memoryOutputTokens: bigint | null, };
