// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpineNodeContextBaselineSource = "provider_at_open" | "root_compact_handoff" | "estimated_from_live_suffix" | "checkpoint_replay";
