// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpineNodeContextBaselineSource } from "./SpineNodeContextBaselineSource";
import type { SpineNodeContextUnavailableReason } from "./SpineNodeContextUnavailableReason";

export type SpineTreeNodeAccounting = { currentNodeContextTokens: bigint | null, currentNodeContextUnavailable: SpineNodeContextUnavailableReason | null, currentNodeContextBaselineSource: SpineNodeContextBaselineSource | null, rawContextTokens: bigint | null, rawInputTokens: bigint | null, memoryOutputTokens: bigint | null, };
