// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpineTreeNodeStatus } from "./SpineTreeNodeStatus";
import type { SpineTreePlan } from "./SpineTreePlan";

export type SpineTreeNode = { nodeId: string, parentId: string | null, summary: string | null, status: SpineTreeNodeStatus, plan: SpineTreePlan | null, };
