// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpineTreePlanItem } from "./SpineTreePlanItem";

export type SpineTreePlan = { revision: bigint, explanation: string | null, items: Array<SpineTreePlanItem>, };
