// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpineTreePlanCheckpoint } from "./SpineTreePlanCheckpoint";
import type { SpineTreePlanItemStatus } from "./SpineTreePlanItemStatus";

export type SpineTreePlanTreeScope = { existingNodeId: string | null, summary: string, status: SpineTreePlanItemStatus | null, checkpoints: Array<SpineTreePlanCheckpoint>, children: Array<SpineTreePlanTreeScope>, };
