// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpineNodeContextUnavailableReason = "missing_current_usage" | "missing_open_context_baseline" | "non_positive_delta" | "corrupt_pressure_metadata";
